//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlytrungtam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int MACHITIETHD { get; set; }
        public Nullable<int> MAHD { get; set; }
        public Nullable<int> MALT { get; set; }
        public string TENLT { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual LOTRINHDUHOC LOTRINHDUHOC { get; set; }
    }
}
