//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlytrungtam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHOADON = new HashSet<CHITIETHOADON>();
        }
    
        public int MAHD { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<int> TINHTRANGHOADON { get; set; }
        public Nullable<int> DATHANHTOAN { get; set; }
        public Nullable<int> MAKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
