//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlytrungtam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCBONG
    {
        public int MAHB { get; set; }
        public string TENHB { get; set; }
        public string ANH { get; set; }
        public string MOTANGAN { get; set; }
        public string MOTACHITIET { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
        public Nullable<decimal> SOTIEN { get; set; }
        public Nullable<int> MANUOC { get; set; }
    
        public virtual NUOC NUOC { get; set; }
    }
}
