//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlytrungtam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHENTUVAN
    {
        public int MALH { get; set; }
        public string HOTEN { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string BUOIHEN { get; set; }
        public string TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> MAKH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
