//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlytrungtam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTRUNGTAMDUHOCEntities1 : DbContext
    {
        public QUANLYTRUNGTAMDUHOCEntities1()
            : base("name=QUANLYTRUNGTAMDUHOCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual DbSet<CHUCVU> CHUCVU { get; set; }
        public virtual DbSet<DANGKYLOTRINH> DANGKYLOTRINH { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<HOCBONG> HOCBONG { get; set; }
        public virtual DbSet<HOSOKHACHHANG> HOSOKHACHHANG { get; set; }
        public virtual DbSet<HOSOVISA> HOSOVISA { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<LICHHENTUVAN> LICHHENTUVAN { get; set; }
        public virtual DbSet<LOTRINHDUHOC> LOTRINHDUHOC { get; set; }
        public virtual DbSet<NUOC> NUOC { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<QUYEN> QUYEN { get; set; }
        public virtual DbSet<TRUONGDAIHOC> TRUONGDAIHOC { get; set; }
    }
}
