//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlytrungtam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUONGDAIHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRUONGDAIHOC()
        {
            this.LOTRINHDUHOC = new HashSet<LOTRINHDUHOC>();
        }
    
        public int MATDH { get; set; }
        public string TENTDH { get; set; }
        public string MOTANGAN { get; set; }
        public string MOTACHITIET { get; set; }
        public string ANH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string TRANG_WEB { get; set; }
        public Nullable<int> MANUOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTRINHDUHOC> LOTRINHDUHOC { get; set; }
        public virtual NUOC NUOC { get; set; }
    }
}
